# .bashrc

#echo "Sourcing akomblevitz's .bashrc"

set -o vi
set -o notify

alias cdb='cd -'
alias cdu='cd ..'
alias cdr='cd .. && cd -'

if [ "$MYOS" == 'Linux' ]; then
   alias ack='ack-grep'
   alias ls='ls --color'
elif [ "$MYOS" == 'OSX' ]; then
   alias ls='ls -G'  # add colors for filetype recognition
elif [ "$MYOS" == 'Cygwin' ]; then
   alias ls='ls --color'
fi

alias psa='ps -ef | ack --noenv --nocolor'

alias vi='vim'
alias df='df -h'
alias ifc='/sbin/ifconfig'

alias l='ls'
alias ll='ls -lh'
alias la='ls -Alh'          # show hidden files
alias lx='ls -lXB'         # sort by extension
alias lk='ls -lSrh'         # sort by size, biggest last
alias lc='ls -ltcr'        # sort by and show change time, most recent last
alias lu='ls -ltur'        # sort by and show access time, most recent last
alias lt='ls -ltr'         # sort by date, most recent last
alias lr='ls -alRh'          # recursive ls
alias tree='tree -Csu'     # nice alternative to 'recursive ls'

#login to service account with my own dotfiles and custom home directory
#ss() {
#    ssh -t "$1"@"$2" ~"$1"/akomblevitz/dotfiles/bin/login_shell_as_akomblevitz.sh
#}

# swap 2 filenames around
swap ()
{
    local TMPFILE=tmp.$$
    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"
}

# Pretty prints your PATH. One entry per line.
ppath () {
    echo $PATH | perl -a -n -F/:/ -e 'foreach (@F) { print "$_\n" }'
}

# Make it easier to mess with $PATH (stolen from Red Hat /etc/profile)
# Helps to keep duplicate pathnames from showing up in your path.
pathmunge () {
        if ! echo $PATH | egrep -s "(^|:)$1($|:)" > /dev/null ; then
           if [ "$2" = "after" ] ; then
              export PATH=$PATH:$1
           else
              export PATH=$1:$PATH
           fi
        fi
}

